### ISSUE TITLE
Need more comperhensive doc

### ISSUE THREAD

**Issue by bedeute** [wmdmark/swig-brunch#1]
Hi, @wmdmark...

I'm noob front end dev and big fan of swig. I consider to try brunch to develop front end. I love your work here. But I think it better to have more comprehensive docs...

so, please create more comprehensive docs...

thanks

**Comment by wmdmark** [comment]
Hi @bedeute,

Since this is just a [Brunch Plugin](http://brunch.io/plugins.html), there's really not much else to document on this end. I would suggest referencing the [Brunch Guide](https://github.com/brunch/brunch-guide#readme) for more information about how Brunch works and uses plugins. I'm happy to chime in on any specific problems you have with this plugin should they arise. 

Cheers!
Mark
